packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-snackbar/ino-snackbar.tsx
packages/elements/src/components/ino-snackbar/readme.md
packages/storybook/src/stories/ino-snackbar/ino-snackbar.stories.js

* Added a new `inoTimeout` property to the `ino-snackbar` component that can be used to modify the time it takes until the snackbar disappears
🎟️ **Resolves:** [ELEMENTS-699](https://jira.inovex.de/browse/ELEMENTS-699)
**Note:** Does not resolve `#81`

feat(elements|ino-snackbar): add property to set custom timeout

---

packages/elements/src/components/ino-switch/ino-switch.scss
packages/elements/src/components/styles/colors.scss
packages/storybook/src/stories/ino-switch/ino-switch.stories.js

* Added color schemes back to `ino-switch` stylesheet
**Closes #84**

fix(elements|ino-switch): fix color-schemes not working correctly

---

doc/framework-integration/javascript-instructions.md
packages/elements/stencil.config.ts

Closes #125 
- Update stencil config to also build for older browsers
- Update integration instruction for javascript
- https://github.com/ionic-team/stencil/issues/2666
- https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-200-2020-08-31
- https://stenciljs.com/docs/config-extras

fix(elements): fix deprecated integration

---

.gitlab-ci.yml

Relates to #110 
- disable the publishing part of the GitLab ci because it is currently not working and we will probably switch to publishing our packages manually

ci: disable publishing via Gitlab CI

---

packages/elements/src/components/ino-fab-set/readme.md
packages/elements/src/components/ino-fab/ino-fab.tsx
packages/elements/src/components/ino-fab/readme.md

Closes #155 
- Wait for `ino-fab` to finish loading
- Create and append `ino-tooltip` element afterward

fix(elements|ino-fab): ensure creation of tooltip after fab loaded

---

packages/elements-angular/elements/package.json

Resolves the following problem in the lerna releasing workflow:
1. Lerna pumps the version of all packages
2. We try to deploy the Angular package with respective `packages/elements-angular/elements/package.json` configuration
3. The configuration states that the distribution config remains within the `../dist` folder.
4. However, in the `../dist` folder there is an outdated package.json
To resolve this, rebuild `elements-angular` before publishing.

chore(*): build angular repo before publishing

---

packages/elements/src/components/ino-table/ino-table.scss
packages/elements/src/components/ino-table/ino-table.tsx

* `ino-table`: disabled the shadow dom
🎟️ **Closes #162**

fix(elements|ino-table): disable shadow dom

---

packages/elements/src/components/ino-card/ino-card.tsx
packages/storybook/src/stories/ino-card/ino-card.stories.js

Closes #206 
- The slots and its containers will only be rendered if there are elements inside the slot

fix(elements|ino-card): render slots only when used

---

packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-input-file/ino-input-file.scss
packages/elements/src/components/ino-input-file/ino-input-file.tsx
packages/elements/src/components/ino-input-file/readme.md
packages/storybook/src/stories/ino-input-file/ino-input-file.scss
packages/storybook/src/stories/ino-input-file/ino-input-file.stories.js

* Added the ability to upload files using a drag and drop window to the `ino-input-file` component
ℹ️ **FYI:**
* There's currently a bug that will result in the event emitter used by the `ino-input-file` component to emit multiple events at once upon setting the action knobs in Storybook to a different value. This bug is also present in other components, such as the `ino-snackbar`(see #81). 
🎟️ **Closes #76**

feat(elements|ino-input-file): add drag and drop window

---

packages/elements/src/components/ino-nav-item/ino-nav-item.scss

Closes #211 
- Deactivate MDC-Ripple effect only on activated nav-items

style(elements|ino-nav-item): disable ripple effect for activated state

---

packages/elements/src/components/ino-datepicker/ino-datepicker.e2e.ts
packages/elements/src/components/ino-datepicker/ino-datepicker.tsx
packages/elements/src/components/ino-datepicker/readme.md
packages/elements/stencil.config.ts
packages/storybook/src/stories/ino-datepicker/ino-datepicker.stories.js

Closes #225 
- A debounce was not possible, because of the multiple possibilities to enter values (e.g. copy/paste, flatpicker)
- It also turned out that validating on blur leads to a worse user experience
- Only validate if flatpicker is set
- Also ino-range validation is fixed

fix(elements|ino-datepicker): use date format to improve validation

---

packages/elements/package.json
packages/storybook/package.json

Closes #228 
- Moves dependency `highlight.js` to storybook instead of elements

refactor: move highlight.js to storybook

---

packages/elements/src/components/ino-button/ino-button.tsx

Closes #195
- The styling of the spinner is bound to the ino-loading attribute somehow. If the property is set using e.g. Angular property binding (<ino-button [inoLoading]="true">...) it results in a modified attribute (ng-reflect-ino-loading) in the DOM, which breaks the styling
- By reflecting the inoLoading property value back to the DOM as HTML attribute (ino-loading), the correct spinner styling can be restored in the Angular use case
- I assume there is a better way to achieve this via the Angular adapter, but I don't really know how the adapter works

fix(elements-angular|ino-button): fix invisible loading spinner

---

packages/elements/src/components/ino-list-item/ino-list-item.tsx

Closes #229
- The text alignment was broken, because the slot for the secondary text was rendered even if no content was provided for this slot (the secondary slot took up space although it was empty)
- This solution only renders the slot if content is provided for this specific slot

fix(elements|ino-list-item): fix text alignment

---

packages/storybook/src/stories/ino-icon/ino-icon.stories.js

Closes #235 
- The chip attribute 'id' (which contains the icon name as 'icon-${name}) is used for the icon search instead of the 'ino-icon' attribute, because this property was removed from the chip component in an earlier PR

fix(storybook|ino-icon): fix icon search

---

packages/elements/src/components/ino-progress-bar/ino-progress-bar.scss

Closes #177 
- Fix progress bar styling and make use of provided mdc sass mixin 
- The styling of the buffer bar and dots should be configurable via the `buffer-color` mixin (`@include linear-progress.buffer-color((var(--progress-bar--buffer-color)));`), but it seems like this only styles the buffer bar correctly, but not the dots.

fix(elements|ino-progress-bar): restore buffer dots

---

packages/elements/src/components/ino-progress-bar/ino-progress-bar.scss
packages/elements/src/components/ino-progress-bar/readme.md
packages/storybook/src/stories/ino-progress-bar/ino-progress-bar.stories.js

Closes #264 
- Add knobs to test properties
- Restore CSS-Var Table
- Remove CSS-Var to color `buffer-dots` because CSS-Vars are not compatible with the mixin provided by MDC

docs(storybook|ino-progress-bar): add customization options and examples

---

packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-nav-item/ino-nav-item.scss
packages/elements/src/components/ino-nav-item/ino-nav-item.tsx
packages/elements/src/components/ino-nav-item/readme.md
packages/storybook/src/stories/ino-list/ino-list.stories.js

Adds a secondary text prop analogous to the ino-list-item

feat(elements|ino-nav-item): add prop for sub text

---

packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-menu/MDCCustomMenu.js
packages/elements/src/components/ino-menu/ino-menu.e2e.ts
packages/elements/src/components/ino-menu/ino-menu.tsx
packages/elements/src/components/ino-menu/readme.md
packages/elements/src/util/e2etests-setup.ts
packages/storybook/src/stories/ino-menu/ino-menu.stories.js

Closes #230 
- Add new event `menuClose` which emits on any click
- Add tests for this new event
- Update wording in Storybook

feat(elements|ino-menu): emit new closeMenu event on click

---

packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-button/ino-button.scss
packages/elements/src/components/ino-button/ino-button.tsx
packages/elements/src/components/ino-button/readme.md
packages/storybook/src/stories/ino-button/ino-button.scss
packages/storybook/src/stories/ino-button/ino-button.stories.js

Closes #251 
- Remove property `ino-full-width` of `<ino-button>`
- Inherit width on button element

style(elements|ino-button): inherit width

---

packages/elements/src/components/ino-menu/ino-menu.scss
packages/storybook/src/stories/ino-menu/ino-menu.scss

* adjusted the `border-radius` property of the `mdc-menu` class to inherit its value from `ino-menu`
🎟️ **Closes #231**

style(elements|ino-menu): inherit border-radius

---

packages/elements/src/components/ino-chip/ino-chip.scss
packages/elements/src/components/ino-chip/ino-chip.tsx
packages/elements/src/components/ino-chip/readme.md
packages/storybook/src/stories/ino-chip-set/ino-chip-set.stories.js

* Added `ino-icon-leading` slot to the `ino-chip` component
🎟️ **Closes #204**

feat(elements|ino-chip): add slot for trailing icon

---

packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-popover/ino-popover.scss
packages/elements/src/components/ino-popover/ino-popover.tsx
packages/elements/src/components/ino-popover/readme.md
packages/elements/src/util/component-utils.ts
packages/storybook/src/stories/ino-popover/ino-popover.scss
packages/storybook/src/stories/ino-popover/ino-popover.stories.js

Relates to #288 
In order to implement a better menu, it should be based on the popover and not on the MDC-Menu.
This PR provides functionalities to manage the state of the popover.
- Add new `ino-controlled` and `ino-show` property which can be used to control the state of the popover
- Add `visibilityChanged` event
- Add slot `ino-popover-trigger`
- Update ReadMe
- Update Storybook entry of the `ino-popover`

feat(elements|ino-popover): add functionality to control component

---

packages/elements/src/components/ino-tooltip/ino-tooltip.tsx

Closes #300 
- Delete watcher that replaced the whole tooltip content including containers

fix(elements|ino-tooltip): updating `ino-label` leads to non-styled text

---

packages/elements/src/components/ino-popover/ino-popover.scss
packages/elements/src/components/ino-popover/ino-popover.tsx

- Use a default `scale` animation provided by tippy

style(elements|ino-popover): use scale-animation as default

---

packages/elements-angular/elements/src/directives/control-value-accesors/text-value-accessor.directive.ts
packages/elements-angular/elements/src/directives/control-value-accesors/value-accessor.directive.ts
packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-textarea/ino-textarea.tsx
packages/elements/src/components/ino-textarea/readme.md

- add `inoBlur` event to `ino-textarea`
- handle `inoBlur` event in `TextValueAccessorDirective` to mark form input and textarea fields as `touched` in combination with angular forms

feat(elements-angular|ino-textarea): handle onTouched in TextValueAccessor

---

packages/elements/src/components/ino-input/ino-input.scss
packages/storybook/src/stories/ino-input/ino-input.stories.js

Cleaned up and restructured the `ino-input.scss` in the hope to make it easier to work on. I structured the stylesheet by text-field variants (default, filled, outlined). There also were some new mixins with the new mdc versions which replaced some complicated selectors.

refactor(elements|ino-input): cleanup styles

---

packages/storybook/src/stories/ino-icon/ino-icon.stories.js

* replaced deprecated `execCommand` function with `navigator.clipboard.writeText`
🎟️ **Closes #279**

refactor(elements|ino-icon): refactor deprecated clipboard function

---

.github/workflows/release-canary.yml

Closes #358 
- Replace github action `actions/download-artifact@v2` with `dawidd6/action-download-artifact@v2` to download artifact from the same workflow run

fix: fix canary-releases

---

.github/workflows/release-canary.yml

Closes #360 
- Check if the current branch is the master branch

fix: run canary release action only in master branch

---

packages/elements/src/components/ino-dialog/ino-dialog.e2e.ts
packages/elements/src/components/ino-dialog/ino-dialog.tsx
packages/elements/src/components/ino-tab-bar/ino-tab-bar.tsx
packages/elements/src/components/ino-tab/ino-tab.tsx

* Removed the event listeners from the `ino-dialog` component since the events were never dispatched due to the missing `data-mdc-dialog-action` attribute (see [mdc-dialog documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-dialog#full-screen-dialog))
* Added stencil's `Listen()` decorator to the `ino-tab` and `ino-tab-bar` components
⚠️ **The `Listen()` decorator can not be used in the following components:**
| Component | Reason |
| ----------- | -------- |
| `ino-nav-drawer` | Event listener is attached to a specific target. The only targets supported by `Listen()` are `window`, `document`, and `body`. |
| `ino-chip-set` | Event listener is only attached in specific cases. |
| `ino-datepicker` | Event listener is …

refactor(elements): use listen decorator

---

packages/storybook/src/stories/ino-snackbar/ino-snackbar.stories.js

Closes #81 
- check if corresponding snackbar already exists before appending it to the DOM on ino-button click

fix(storybook|ino-snackbar): avoid multiple snackbar instances

---

packages/elements/src/components/ino-datepicker/validator.spec.ts
packages/elements/src/components/ino-datepicker/validator.ts

* Add validation for range dates such that the second one is large than the first one
* Restructure tests
* Ignore errors on wrong dateformats if the user ist still typing

feat(elements|ino-datepicker): validate if first < second date

---

packages/elements/src/components/ino-control-item/ino-control-item.scss
packages/elements/src/components/ino-list/ino-list.scss
packages/elements/src/components/ino-list/readme.md
packages/storybook/custom-elements.json

Closes #364 
- Add CSS-Var `--border-radius` to give the container of the `ino-list` a border-radius
- Also affects the first and last `ino-(list|control)-item` in the list

style(elements|ino-list): add css variable for border radius

---

packages/elements/src/components/ino-select/ino-select.tsx
packages/elements/tsconfig.json
packages/storybook/config/global.scss

✨ Features:
uses visually hidden <select> element instead of <input>
🎟️ Closes #348

fix(elements|ino-select): fix form validation

---

packages/elements/src/components/ino-tab-bar/ino-tab-bar.tsx

Closes #196 
- `focusOnActivate` property is set to `false` on creation

fix(elements|ino-tab-bar): prevent autofocus on creation

---

packages/elements/src/components/ino-select/ino-select.e2e.ts
packages/elements/src/components/ino-select/ino-select.scss
packages/elements/src/components/ino-select/ino-select.tsx
packages/storybook/config/global.scss
packages/storybook/src/stories/ino-select/ino-select.stories.ts

Closes #414. Basically reverts https://github.com/inovex/elements/pull/355 and fixes https://github.com/inovex/elements/issues/348 properly.
- Revert to using a hidden input instead of select
- Move hidden input to prevent collision with mdc select internal logic
- Add tests to confirm correct form submission handling
- Add a story to test form submission

fix(elements|ino-select): hide input used for form validation

---

.prettierignore
packages/elements-angular/elements/src/app-initialize.ts
packages/elements/package.json
packages/elements/src/components/base/_typography.scss
packages/elements/src/util/import-fonts.ts
packages/storybook/custom-elements.json
yarn.lock

Closes #160 
- provide global css var `--ino-font-family` for custom font
- loading _Lato_ font from static inovex host if necessary

refactor: load font `lato` from inovex host

---

packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-label/ino-label.scss
packages/elements/src/components/ino-label/ino-label.tsx
packages/elements/src/components/ino-select/ino-select.scss
packages/elements/src/components/ino-select/ino-select.tsx
packages/elements/src/components/ino-select/readme.md
packages/storybook/custom-elements.json
packages/storybook/src/stories/ino-select/ino-select.stories.ts

Relates to #423
- add Property `error` to enable error state programmatically

feat(elements|ino-select): add property `error` to display error state

---

packages/elements/src/components/ino-autocomplete/ino-autocomplete.tsx

Closes /
- `setupOptions` might be called before `setupInput`, so setting the value of the input won't always work
- set value of slotted `<ino-input>` on `setupInput` as well

fix(elements|ino-autocomplete): set value on initialization

---

packages/elements-angular/elements/src/directives/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-snackbar/ino-snackbar.tsx
packages/elements/src/components/ino-snackbar/readme.md
packages/storybook/custom-elements.json
packages/storybook/src/stories/ino-snackbar/ino-snackbar.stories.ts

**Target branch is not the 'master'** branch !
<hr />
* Relates to #403 
* remove `message` property from ino-snackbar 
* using default slot for message

refactor(elements|ino-snackbar): use default slot instead of property

---

packages/elements/src/components.d.ts
packages/elements/src/components/ino-input/ino-input.tsx
packages/elements/src/components/ino-input/readme.md
packages/storybook/elements-stencil-docs.json

Resolves Bug depening on Angular lifecycle:
- Check wheter `this.textfield` extits by setting the error property.

fix(elements|ino-input): prevent undefined reference on error set

---

packages/elements/src/components/ino-datepicker/ino-datepicker.tsx

Resolves Bug depening on Angular lifecycle:
- check if target HTML elements exitsts before initializing flatpickr

fix(elements|ino-datepicker): prevent undefined ref on mount

---

packages/elements/src/components/ino-autocomplete/ino-autocomplete.scss
packages/elements/src/components/ino-autocomplete/ino-autocomplete.tsx

- change css styles to prevent floating option list container
- default `max-height` is set to `225px` equals to height of 6 list options

fix(elements|ino-autocomplete): fix positioning while scrolling

---

packages/elements/src/components/ino-datepicker/ino-datepicker.tsx

- Support reattaching of datepicker by calling `this.create()` in `connectedCallback`

fix(elements|ino-datepicker): reattach on DOM update

---

packages/elements/package.json
packages/storybook/elements-stencil-docs.json
packages/storybook/package.json
yarn.lock

- Remove unused dependency `node-sass`
- Is necessary to make the elements repository work with the M1 as `node-sass` is deprecated and thus does not have binaries for that chip
- upgrade `@stencil/core` to latest version (`2.14.0`)
- necessary because of `puppeteer` peer-dependency which got upgraded from `5.x.x` to `10.x.x`
- `puppeteer` must be at least at version 9 to work on M1 macs (see https://github.com/puppeteer/puppeteer/issues/6622)

chore(deps): upgrade deps to support M1 chips

---

packages/elements/src/components/ino-markdown-editor/ino-markdown-editor.e2e.ts
packages/elements/src/components/ino-markdown-editor/ino-markdown-editor.tsx

- add new watcher function for property `initialValue`

fix(elements|ino-markdown-editor): handle change of `initialValue`

---

packages/landingpage/src/views/WelcomeIndex.vue
packages/storybook/src/stories/docs/styleguide/styles.scss

Closes #532 
- Remove the fonts hosted by Google in the following packages:
- `landingpage`
- `storybook`
- No replacement is needed because the fonts were not in use

chore: remove fonts hosted by google

---

packages/elements/src/components/base/_typography.scss

- The `/` operator is will be deprecated with the next major version of SASS
- Replace `/` with `math.div(...)`

refactor(elements): replace deprecated division operator

---

packages/elements/src/components/ino-nav-item/ino-nav-item.scss

Closes #549 
- the `<ino-nav-item>` is based on the `mdc-list-item`
- the classes of `mdc-list-item` changed with #349 but the `<ino-nav-item>` has not received an update
- replace classes `mdc-list-item-...` with `mdc-deprecated-list-item-...`

style(elements|ino-nav-item): fix styles not being applied

---

packages/elements/src/components/ino-chip/ino-chip.scss

When the `<ino-icon>` in the trailing slot of the `<ino-chip>` has a custom height or width (e.g. by setting `--ino-icon-width`), the ripple effect is not aligned correctly.
see:
- align the icon correctly so the ripple effect has the correct position

style(elements|ino-chip): align hover effect even if css vars are used

---

packages/elements/src/components/ino-chip/ino-chip.tsx

- the `chipRemoved` event was not triggered if the icon was not clicked directly but the hover animation indicated a bigger radius

fix(elements|ino-chip): fix `chipRemoved` event not firing in some cases

---

packages/elements/src/components/ino-autocomplete/ino-autocomplete.tsx

A quick fix in order to expose information about the status of the menu (visible/hidden) and the filter status (options found/no options found).

refactor(elements|ino-autocomplete): expose menu and empty status

---

packages/elements/json-docs-output-target.ts
packages/elements/stencil.config.ts
packages/storybook/elements-stencil-docs.json

- The core package generates a JSON-File with each build (`packages/storybook/elements-stencil-docs.json`) describing all components and properties
- This file includes a `timestamp` of its generation that **always** leads to merge conflicts
- I wrote a custom output target that deletes the `timestamp` (and other irrelevant props) before writing to the file

build(elements): delete timestamp from json docs

---

packages/elements/src/components/ino-icon-button/ino-icon-button.scss
packages/elements/src/components/ino-icon-button/ino-icon-button.tsx
packages/elements/src/components/ino-icon-button/readme.md
packages/storybook/src/stories/ino-icon-button/ino-icon-button.stories.ts

Closes #513 
- specify styling for disabled state
- add CSS properties for button background and icon in disabled state
- add exemplary CSS properties story

fix(elements|ino-icon-button): improve button styling in disabled state

---

.github/workflows/deploy-react-example.yml

A new git-workflow needs to be deployed to the master in order to be installed as a git action.
This action will deploy the react-example-project to gh-pages.

ci: add action to deploy elements-react-example project

---

.github/workflows/deploy-vue-example.yml

A new git-workflow needs to be deployed to the master in order to be installed as a git action.
This action will deploy the vue-example-project to gh-pages.

ci: add action to deploy elements-vue-example project

---

.github/workflows/deploy-angular-example.yml

A new git-workflow needs to be deployed to the master in order to be installed as a git action.
This action will deploy the angular-example-project to gh-pages.

ci: add action to deploy elements-angular-example project

---

packages/elements/package.json
packages/elements/src/components.d.ts
packages/elements/stencil.config.ts
packages/storybook/elements-stencil-docs.json
yarn.lock

Closes #659 
- [stencil seems not to fully support alternative builders like vite](https://github.com/ionic-team/stencil/issues/2827)
- With version 2.16.0 they added an experimental flag to the stencil config which seems to work in our case

deps: bump stencil to support builders like vite

---

packages/elements/src/components/ino-datepicker/ino-datepicker.tsx

Fixes this warning which occurs on every render:

fix(elements|ino-datepicker): run initial validation before load

---

packages/storybook/config/manager.js

docs(storybook): collapse component roots by default

---

packages/elements/src/components/ino-carousel/ino-carousel.e2e.ts
packages/elements/src/components/ino-option/ino-option.tsx
packages/elements/src/components/ino-select/ino-select.e2e.ts
packages/elements/src/components/ino-select/ino-select.tsx

fix(elements|ino-select): prevent the `valueChange` event from triggering initially and triggering twice

---

.github/workflows/deploy-unicorn.yml
.github/workflows/destroy-unicorn.yml
.github/workflows/test.yml

ci: optimize unicorn deployment

---

packages/elements-angular/elements/src/directives/proxies.ts
packages/elements-vue/src/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-carousel/ino-carousel.e2e.ts
packages/elements/src/components/ino-chip/ino-chip.scss
packages/elements/src/components/ino-chip/ino-chip.tsx
packages/elements/src/components/ino-chip/readme.md
packages/storybook/elements-stencil-docs.json
packages/storybook/src/stories/ino-chip/ino-chip.stories.ts

style(elements|ino-chip): update design

---

.github/workflows/artifacts-download/action.yml
.github/workflows/deploy-version.yml

Closes #831 
- adjust configuration for downloading artifacts
- use `check_artifacts` option
- use `workflow_conclusion` option
- for details see https://github.com/dawidd6/action-download-artifact

ci: use artifacts from current workflow run

---

packages/elements/src/components/ino-icon-button/ino-icon-button.scss

In the refactoring #736, the `--ino-icon-button-icon-color` have been hardcoded on the element root level. This might not be a problem using the element directly. However, inside the shadow DOM (for example `ino-nav-drawer`), one cannot override the properties anymore because the `ino-icon-button` styles itself are not accessible.
Thus, the css vars should only provide a default value and not be hardcoded :)

fix(elements|ino-icon-button): remove hardcoded css variables

---

.github/workflows/deploy-landingpage-new.yml
.github/workflows/deploy-landingpage.yml
.github/workflows/deploy-version.yml
.github/workflows/test.yml
packages/landingpage-new/pages/about/index.tsx

Closes #841 
- Our new landingpage pulls our latest activity via the official Github API
- This fetch happens locally with every reload in dev and once at build time in prod
- While it is possible to fetch the data without a token, we ran into rate limits when using the Github runners to build the app (presumably because the runner or its IP was already used for API calls)
- With this PR, our Github tokens will be used when running the build process via the Github pipeline

fix(landingpage): use GitHub token to fetch commits if available

---

packages/landingpage-new/components/home/faq-section/faq-section.module.scss
packages/landingpage-new/components/home/faq-section/faq-section.tsx
packages/landingpage-new/pages/[lang]/index.tsx
packages/landingpage-new/translations/locales/de/home.json
packages/landingpage-new/translations/locales/en/home.json
packages/landingpage-new/utils/elementsWrapper.ts

Closes #817
**Error Report**[FIXED]:
The ino-accordion component is not rendering properly after the locale switcher is changed or on the initial page load once we listen to the default locale in localeStorage, which calls [`useMount(redirectToDefaultLocale)`](url) in the` index.tsx `file. The text of the FAQ section is displayed as plain text, but the component that should display the text is not being rendered properly. This is causing an issue with the layout and functionality of the FAQ section.
https://user-images.githubusercontent.com/81302108/219409323-83af2ef3-1429-4296-8b79-54eca32c989a.mp4
As shown in the video it only happens for the ino-accordion component, inspecting the element it still renders as ino-carousel in the dev-tools. 
Giving the slot content Fragments(`<> Bla …

feat(landingpage): add faq to landingage

---

packages/elements/src/components/ino-accordion/ino-accordion.scss
packages/elements/src/components/ino-accordion/ino-accordion.tsx
packages/storybook/src/stories/ino-accordion/ino-accordion.stories.ts

This PR refactors our ino-accordion component, drawing from a [blog post](https://keithjgrant.com/posts/2023/04/transitioning-to-height-auto/) to implement smoother transitions. By transitioning to height auto with grid, I have optimized the toggling of the expanded state. This results in cleaner code and improved user experience in my opinion as now we avoid the instant expanding of the accordion and fade in text solution from before.
Before & After:
https://github.com/inovex/elements/assets/81302108/edaaff25-05cc-4576-92a3-d10d481dc111

refactor(elements|ino-accordion): optimize transition

---

packages/elements-angular/src/directives/proxies.ts
packages/elements-vue/src/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-icon-button/ino-icon-button.tsx
packages/elements/src/components/ino-icon-button/readme.md
packages/elements/src/components/ino-list-item/ino-list-item.tsx
packages/elements/src/components/ino-list-item/readme.md
packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.tsx
packages/elements/src/components/ino-nav-drawer/readme.md
packages/elements/src/components/ino-nav-item/readme.md
packages/elements/src/components/types.ts
packages/storybook/elements-stencil-docs.json
packages/storybook/src/stories/ino-nav-drawer/ino-nav-drawer.stories.ts

Closes https://github.com/inovex/elements/issues/979
- Add aria-labels to nav elements
- Refactor use proper semantics
- Adjust nav-drawer story to show correct usage

feat(elements|ino-nav-drawer): accesibility improvements

---

packages/storybook/config/global.scss
packages/storybook/config/manager-head.html
packages/storybook/config/preview-head.html
packages/storybook/config/theme.js

Closes #965
- add & use new color theme in storybook

refactor(storybook): use new stylesheet for storybook

---

packages/elements-angular/src/directives/proxies.ts
packages/elements-vue/src/proxies.ts
packages/elements/src/components.d.ts
packages/elements/src/components/ino-currency-input/ino-currency-input.e2e.ts
packages/elements/src/components/ino-datepicker/ino-datepicker.e2e.ts
packages/elements/src/components/ino-input/ino-input.e2e.ts
packages/elements/src/components/ino-input/ino-input.tsx
packages/elements/src/components/ino-label/ino-label.tsx
packages/elements/src/components/ino-label/readme.md
packages/elements/src/components/ino-textarea/ino-textarea.tsx
packages/storybook/elements-stencil-docs.json

Closes #...
- add 'for' attribute to ino-label component
- inp-input: fix orphaned label error 
- ino-textarea: fix orphaned label error

feat(elements|ino-label): add for attribute to link from controls

---

packages/elements/src/components/base/_tooltip-base.scss
packages/elements/src/components/base/_tooltip_base.scss
packages/elements/src/components/ino-chip/ino-chip.scss
packages/elements/src/components/ino-datepicker/ino-datepicker.scss
packages/elements/src/components/ino-fab/ino-fab.scss
packages/elements/src/components/ino-icon-button/ino-icon-button.scss
packages/elements/src/components/ino-input/ino-input.scss
packages/elements/src/components/ino-list-divider/ino-list-divider.scss
packages/elements/src/components/ino-list-item/ino-list-item.scss
packages/elements/src/components/ino-markdown-editor/ino-markdown-editor.scss
packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.scss
packages/elements/src/components/ino-nav-item/ino-nav-item.scss
packages/elements/src/components/ino-progress-bar/ino-progress-bar.scss
packages/elements/src/components/ino-range/ino-range.scss
packages/elements/src/components/ino-segment-button/ino-segment-button.scss
packages/elements/src/components/ino-select/ino-select.scss
packages/elements/src/components/ino-snackbar/ino-snackbar.scss
packages/elements/src/components/ino-spinner/ino-spinner.scss
packages/elements/src/components/ino-tab/ino-tab.scss
packages/elements/src/components/ino-table-header-cell/ino-table-header-cell.scss
packages/elements/src/components/ino-table/_table-row.scss
packages/elements/src/components/ino-table/ino-table.scss
packages/elements/src/components/ino-textarea/ino-textarea.scss

Closes #859 
- use new color scheme in the following components
ino-autocomplete
ino-currency-input
ino-datepicker
ino-input
ino-markdown-editor
ino-option-group
ino-option
ino-range
ino-select
ino-textarea
ino-chip
ino-fab-set
ino-icon-button
ino-segment-button
ino-segment-group
ino-control-item
ino-list-divider
ino-list-item
ino-list
ino-menu
ino-nav-drawer
ino-nav-item
ino-tab-bar
ino-tab
ino-table-header-cell
ino-table
ino-progress-bar
ino-nackbar
ino-spinner
ino-tooltip

style(elements): use new color scheme

---

packages/elements/src/components/ino-input/ino-input.scss
packages/elements/src/components/ino-select/ino-select.scss

Closes #1037 
Instead of disabling tailwinds preflight styles we can override it with our own custom css like so:
`ino-select * {
border-style: none;
}
`
more about this here: https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally
Preview(before and after the changes):
https://github.com/inovex/elements/assets/81302108/6c9223ce-9893-43f5-a53d-a299c2d63db3

fix(elements): override tailwind css preflight border-styles

---

packages/elements/src/components/ino-snackbar/ino-snackbar.tsx

Closes #994 
- improved a11y of the snackbar component by adding the role "alert" to the outer container

feat(elements|ino-snackbar): improve a11y

---

.github/workflows/deploy-prerelease.yml
.github/workflows/deploy-storybook.yml
nx.json
package.json
scripts/publish.ts

Closes #1196 
- use `preid` flag for prereleases
- skip unstable versions for calculating new release version
- skip prerelease workflow when normal release was executed

ci: fix calculation of release version

---

.github/workflows/deploy-prerelease.yml
scripts/publish.ts

Closes #1197 
- provide code paths 
- exit gracefully in check tag step in prerelease workflow
A workspace changelog only with changes that relates to the npm libraries is currently not possible. By creating a project-based changelog this is possible.

ci: use only npm libraries for next version calculation

---

packages/storybook/src/stories/docs/styleguide/styles.scss
packages/storybook/src/stories/docs/styleguide/typography.stories.mdx

Closes #1128
- Problem was that MDX created a `<p>` when a text was broken in a new line, e.g.:
```mdx
<div>
<h1>
My totally valid Headline
</h1>
</div>
```
was parsed to 
```html
<div>
<h1>
<p>My totally valid Headline</p>
</h1>
</div>
```

fix(storybook): restore typography page

---

packages/elements/src/components/ino-icon/ino-icon.scss
packages/elements/src/components/ino-icon/readme.md

Closes #1172 
- set `vertical-align: middle` on ino-icon element

fix(elements|ino-icon): improve vertical alignment

---

packages/elements/src/components/ino-markdown-editor/ino-markdown-editor.scss

Closes #1194 
- remove `p` spacing for `ul` and `ol` too

fix(elements/ino-markdown-editor): adjust list spacings

---

packages/landingpage/components/layout/header/mobile/header.mobile.module.scss
packages/landingpage/components/layout/header/mobile/header.mobile.tsx
packages/landingpage/components/layout/linkItem.module.scss

Closes #1188 
- align text and icon of mobile muenu item vertically
- optimzie spacing in mobile menu to prevent letter break in german

fix(landingpage): align mobile menu item content vertically

---

packages/storybook/playwright.config.ts
packages/storybook/project.json

Improve pipeline configs:
- `forbidOnly`: useful because often forgotten
- `globalTimeout`: increase the timeout to cope with reduced performance of random github runner
- `quiet`: Prevent spam of output
- `passWithNoTests`: prevents false positives if for some reason test were not executed properly
- `skipInstall`: We check if playwright was installed before in order to restore the cache -> should save some time

refactor(storybook): improve testing config in pipeline

---

packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.e2e.ts
packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.tsx

Closes #1204 
- reinitialize instance of MDCDrawer on variant change

fix(elements/ino-nav-drawer): reinit listeners properly when switching between variants 

---

packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.scss
packages/elements/src/components/ino-nav-item/ino-nav-item.scss
packages/storybook/src/stories/ino-nav-drawer/ino-nav-drawer.spec.ts

Closes #1202 & #1205
I've adjusted the ino-nav-items to follow our typography preset (`label-l`). For the mobile ino-nav-drawer, I've matched the font sizes to the default settings but opted for slightly smaller icons to maintain balance. I tested a range of phone sizes to guarantee the design remains intuitive and readable in different environments.
>- [x] The font size of the subtitle has been increased. 
Previously, it was 12px, but it has now been updated to 14px (`label-l`). Due to this the primary text is bigger by 2px but keeps the same font weight (Refer to the attached screenshot below for details, 150% zoom.) 
> - [x]  Font size for the mobile variant in ino-nav-drawer is increased to an appropriate and readable level.
> - [x]  The adjustment maintains a visually consistent and …

refactor(elements/ino-nav-drawer): switch to a bigger typography preset

---

packages/landingpage/utils/routes.tsx

Closes #1300
allows for routing to the patterns section under library on the landingpage, Merge after #1281

refactor(landingpage): enable UI Patterns route 

---

packages/landingpage/app/[lang]/explore/_components/examples.tsx

Hot fix for ino-icon-buttons because icons where misaligned

fix(landingpage): hotfix ino-icon-buttons

---

.github/workflows/deploy-release.yml
.github/workflows/deploy-storybook.yml

Closes #1277
Because we checkout the `pages` branch, we are not able to build the storybook directly. But I align the deployment of the storybook with the landingpage deployment.
**To be discussed**
Now I need a version as input for the deployment. But we can omit this.
To do this we can read the latest version from the root `package.json`. Same as now in the release workflow (see changes). During this it is not possible to deploy an other version than the latest one, but I do not know if this is needed.
- provide manual storybook deployment
- deploy storybook with release workflow

ci: deploy storybook in release workflow

---

packages/elements/src/components/ino-list-item/ino-list-item.spec.ts

Part of #1258 
- migrate existing stencil e2e tests to jest spec tests

refactor(elements/ino-list-item): migrate stencil e2e tests to jest spec tests

---

packages/elements/src/components/ino-button/ino-button.scss
packages/elements/src/components/ino-chip/ino-chip.scss
packages/elements/src/components/ino-icon-button/ino-icon-button.scss
packages/elements/src/components/ino-icon/ino-icon.scss
packages/elements/src/components/ino-select/ino-select.scss
packages/storybook/src/stories/ino-button/ino-button.scss

Closes #1340
- Added `vertical-alignment: middle;` to the ino-icon.
- Adjusted alignment settings for all parent components that are affected by this change to ensure consistent vertical alignment
Parent components that needed adjustment:
other components like the ino-avatar didnt need any refactoring

refactor(elements): align ino-icon vertically and adjust parent components for consistency
