- doc/contributing/01-high-level-overview.md
- doc/contributing/02-quick-start.md
- doc/contributing/03-team-organization.md
- doc/contributing/04-developing-components.md
- doc/contributing/05-storybook.md
- doc/contributing/06-issue-tracking.md
- doc/contributing/07-commit-message-format.md
- doc/contributing/08-pull-requests.md
- doc/contributing/09-versioning-and-releasing.md
- doc/contributing/10-updating-dependencies.md
- doc/framework-integration/angular-instructions.md
- doc/framework-integration/javascript-instructions.md
- doc/welcome.md
⚙️ changes:
- fixed some spelling mistakes
- changed the grammatical structure of some sentences
- resolved grammatical contractions (e. g. don't to do not)
- applied the Oxford comma
> docs: improve documentation

- packages/elements/src/components/ino-header/ino-header.scss
- packages/elements/src/components/ino-header/readme.md
- packages/storybook/src/stories/ino-header/ino-header.stories.js
* Added CSS variables to `ino-header` component
🎟️ **Resolves:** [ELEMENTS-700](https://jira.inovex.de/browse/ELEMENTS-700)
> feat(elements|ino-header): add css variables 

- packages/elements/src/components/ino-segment-button/constants.ts
- packages/elements/src/components/ino-segment-button/ino-segment-button.scss
- packages/elements/src/components/ino-segment-button/ino-segment-button.tsx
- packages/elements/src/components/ino-segment-button/readme.md
- packages/storybook/src/stories/ino-segment-button/ino-segment-button.stories.js
- packages/storybook/src/stories/ino-segment-group/ino-segment-group.stories.js
⚙️ **changes:**
* Added CSS variables to the `ino-segment-button` component
🎟️ **resolves:** ELEMENTS-604
> feat(elements|ino-segment-button): add css variables

- packages/elements/src/components/ino-icon/readme.md
- packages/elements/src/components/ino-option/ino-option.scss
- packages/elements/src/components/ino-option/readme.md
- packages/storybook/src/stories/ino-select/ino-select.stories.js
⚙️ **changes:**
* added support for css variables to the `ino-option` component
🎟️ **resolves:** ELEMENTS-602
> feat(elements|ino-option):  add css variables

- packages/elements/src/components/ino-list-item/ino-list-item.scss
- packages/elements/src/components/ino-list-item/readme.md
- packages/storybook/src/stories/ino-list/ino-list.stories.js
⚙️ **changes:** added css variables to `ino-list-item` component
🎟️ **resolves:** ELEMENTS-601
> feat(elements|ino-list-item): add css variables

- packages/storybook/src/stories/showcase/showcase.stories.js
* fix typo in link to `ino-nav-drawer` component
**Closes #122**
> fix(storybook|ino-nav-drawer): fix broken link

- packages/elements-angular/elements/src/directives/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-card/ino-card.scss
- packages/elements/src/components/ino-card/ino-card.tsx
- packages/elements/src/components/ino-card/readme.md
- packages/storybook/src/stories/ino-card/ino-card.stories.js
* Added a new `inoDisableHover` property to the `ino-card` component that can be used to disable the hover effect
**Closes #65**
> feat(elements|ino-card): add property to disable hover animation

- doc/framework-integration/angular-instructions.md
- doc/framework-integration/react-instructions.md
- doc/framework-integration/vue-instructions.md
Closes #69 
- Add links to codesandboxes of example projects
> docs(storybook): add links to examples projects in codesandbox

- packages/elements/src/components/ino-icon/icon-assets/SVG/refresh.svg
- packages/elements/src/components/ino-icon/icons.js
- packages/storybook/static/icon-assets/SVG/refresh.svg
- add a refresh icon ![image](https://user-images.githubusercontent.com/22963121/95969652-4af80a80-0e0f-11eb-94d8-c02af4411648.png)
> feat(elements|ino-icon): add refresh icon

- packages/elements/src/components/ino-card/readme.md
- packages/elements/src/components/ino-fab/readme.md
- packages/storybook/src/stories/ino-card/ino-card.stories.js
- packages/storybook/src/stories/ino-fab-set/ino-fab-set.stories.js
Closes #
Update ino-fab and ino-card docu and remove former ino-color-scheme api
> docs(storybook): update ino-fab and ino-card documentation

- packages/elements-angular/angular.json
- packages/elements-angular/elements/ng-package.json
- packages/elements-angular/elements/ngcc.config.js
- packages/elements-angular/elements/src/app-initialize.ts
- packages/elements-angular/elements/src/ino-elements.module.ts
- packages/elements-angular/package.json
- scripts/publishAngular.sh
> fix(elements-angular): add compatibility for ivy support

- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.tsx
> chore(elements): remove relative css import path

- packages/elements/src/components/ino-card/readme.md
- packages/elements/src/components/ino-fab/readme.md
These files change when running the build process.
> docs(elements): update auto generated docs of ino-card and -fab

- CHANGELOG.md
- packages/elements-angular/CHANGELOG.md
- packages/elements-angular/elements/CHANGELOG.md
- packages/elements-react/CHANGELOG.md
- packages/elements/CHANGELOG.md
- packages/storybook/CHANGELOG.md
Closes #148 
- Remove duplicated entries in Changelogs
> chore(*): remove duplicated entries in the changelog

- packages/elements/src/components/ino-card/ino-card.scss
- packages/elements/src/components/ino-chip/ino-chip.scss
- packages/elements/src/components/ino-fab/ino-fab.scss
- packages/elements/src/components/ino-icon-button/ino-icon-button.scss
- packages/elements/src/components/ino-input/ino-input.scss
- packages/elements/src/components/ino-list-item/ino-list-item.scss
- packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.scss
- packages/elements/src/components/ino-popover/ino-popover.scss
- packages/elements/src/components/ino-progress-bar/ino-progress-bar.scss
- packages/elements/src/components/ino-range/ino-range.scss
- packages/elements/src/components/ino-select/ino-select.scss
- packages/elements/src/components/ino-snackbar/ino-snackbar.scss
- packages/elements/src/components/ino-spinner/ino-spinner.scss
- packages/elements/src/components/ino-switch/ino-switch.scss
- packages/elements/src/components/ino-tab/ino-tab.scss
- packages/elements/src/components/ino-table-row/ino-table-row.scss
- packages/elements/src/components/ino-textarea/ino-textarea.scss
- packages/elements/src/components/ino-tooltip/ino-tooltip.scss
- packages/elements/src/components/styles/colors.scss
- packages/storybook/src/stories/ino-switch/ino-switch.scss
- Make all variables in `color.scss` private
- Update usage to use the `ino-color` function
- Rename variables
> refactor(elements): make color variables private

- packages/elements/src/components/ino-checkbox/ino-checkbox.scss
- packages/elements/src/components/ino-checkbox/ino-checkbox.tsx
- packages/storybook/src/stories/ino-checkbox/ino-checkbox.stories.js
- packages/storybook/src/stories/ino-table/ino-table.stories.js
> feat(elements|ino-checkbox): add indeterminate state for selection checkbox

- packages/elements/src/components/ino-chip/ino-chip.scss
- packages/elements/src/components/ino-input/ino-input.scss
- packages/storybook/src/stories/ino-dialog/ino-dialog.stories.js
> fix(elements): allow setting of box-sizing to border-box

- packages/elements-angular/elements/src/directives/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-icon-button/ino-icon-button.scss
- packages/elements/src/components/ino-icon-button/ino-icon-button.tsx
- packages/elements/src/components/ino-icon-button/readme.md
- packages/storybook/src/stories/ino-icon-button/ino-icon-button.stories.js
Requires some attention:
=> More tests for state color changes
=> Requires Update to MDC8.0 first!
> feat(elements|ino-icon-button): add managed option and provide customization options

- doc/framework-integration/angular-instructions.md
Updates docu on how to use elements with angular
> docs: update angular usage docs

- .github/workflows/github-ci.yml
Closes #184 
- Cache dependencies installed by `yarn install`
- ~Cache build artifacts~ -> No use-case atm
> ci: cache dependencies inbetween jobs

- packages/elements-react/src/components/index.ts
- Exports the `ino-carousel` and `ino-carousel-slide` components in the react wrapper
> fix(elements-react): export ino-carousel/-slide components

- packages/elements/src/components/ino-card/readme.md
* Updated the `ino-card` readme to reflect previous changes to the component structure
🎟️ **Closes #186**
> docs(elements|ino-card): update deprecated examples

- packages/elements/src/components/ino-img/ino-img.tsx
* Added a NaN check prior to setting the image dimensions
🎟️ **Closes #187**
> fix(elements|ino-img): fix rendering issue if dimensions are not set

- packages/elements-angular/elements/src/directives/angular-component-lib/utils.ts
- packages/elements-angular/elements/src/directives/proxies-utils.ts
- packages/elements-angular/elements/yarn.lock
- packages/elements/angular-target-fix.ts
- packages/elements/stencil.config.ts
Closes #164
Duplicate to run checks on this branch.
See #170 for discussion
> fix(elements-angular): prevent events from firing twice

- packages/elements/src/components/ino-table/readme.md
* Updated the `ino-table` readme to reflect previous changes
🎟️ **Closes #146**
> docs(elements|ino-table): update outdated readme

- .github/workflows/github-ci.yml
- .yarnrc
- lerna.json
- package.json
Closes #167 
- Add script to create a canary release
- Run this script with every push to master in Github CI
> ci: enable canary releases

- package.json
- Add release script to `package.json`
> chore: add npm release script

- package.json
- packages/elements-angular/elements/yarn.lock
- packages/elements/package.json
- packages/elements/src/components/ino-input/ino-input.tsx
- packages/elements/tslint.json
- yarn.lock
Closes #46 
Currently, we do not pass down the autofocus prop to the input element.
> fix(elements|ino-input): add autofocus prop to input element

- packages/elements/src/components/ino-fab-set/ino-fab-set.scss
- packages/elements/src/components/ino-fab/ino-fab.scss
Closes #
- Syntax error
- Resolves https://github.com/inovex/elements/issues/218 & https://github.com/inovex/elements/issues/212
> fix(elements|ino-fab): restore disabled color

- packages/elements/src/components/ino-datepicker/ino-datepicker.tsx
- packages/elements/src/components/ino-input/ino-input.e2e.ts
- packages/elements/src/components/ino-input/ino-input.tsx
- packages/storybook/src/stories/ino-datepicker/ino-datepicker.stories.js
Closes #205 
- abort click and error handling when datepicker is disabled (as suggested in the issue description)
> fix(elements|ino-datepicker): prevent interaction with disabled datepicker and fix validation

- packages/elements/src/components/ino-list-item/ino-list-item.tsx
Closes #259 
- Prevent `ino-list-item` from destroying itself when unmounted
> fix(elements|ino-list-item): prevent destruction on unmount

- packages/elements/src/components/ino-datepicker/ino-datepicker.tsx
- packages/elements/src/components/ino-datepicker/local.ts
- packages/storybook/src/stories/ino-datepicker/ino-datepicker.stories.js
Closes #256 
- Add automatic language support for datepicker (thanks @pfecht)
> feat(elements|ino-datepicker): add language support

- packages/elements/package.json
- yarn.lock
- update `@stencil/core` to `2.4.0`
- update `stencil/sass` to `1.4.0`
> chore(elements): update stencil/core and stencil/sass

- packages/elements/src/components/ino-popover/ino-popover.scss
- packages/storybook/src/stories/ino-popover/ino-popover.scss
- packages/storybook/src/stories/ino-popover/ino-popover.stories.js
Closes #290 
- Move the padding of the ino-popover to its story
> style(elements|ino-popover): remove default paddings

- packages/elements/src/components/ino-datepicker/ino-datepicker.tsx
> fix(elements|ino-datepicker): fix default date

- packages/elements-angular/elements/src/directives/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-menu/MDCCustomMenu.js
- packages/elements/src/components/ino-menu/ino-menu.e2e.ts
- packages/elements/src/components/ino-menu/ino-menu.scss
- packages/elements/src/components/ino-menu/ino-menu.tsx
- packages/elements/src/components/ino-menu/readme.md
- packages/elements/src/components/ino-popover/ino-popover.scss
- packages/elements/src/components/ino-popover/readme.md
- packages/elements/src/components/ino-tooltip/ino-tooltip.scss
- packages/elements/src/components/ino-tooltip/mixins.scss
- packages/elements/src/util/component-utils.ts
- packages/storybook/src/stories/ino-menu/ino-menu.scss
- packages/storybook/src/stories/ino-menu/ino-menu.stories.js
Reverts inovex/elements#294
I forgot to write Breaking Changes in the body of the commit message. In order to avoid force pushing an edited commit or merging an empty PR, I'll revert these changes and reopen a new PR with the same changes.
> Revert "refactor(elements|ino-menu): replace underlying mdc-menu with ino-popover"

- packages/storybook/src/stories/ino-snackbar/ino-snackbar.stories.js
* fixed incorrect values for `ino-alignment` knob options
🎟️ **Closes #280**
> fix(storybook|ino-snackbar): fix incorrect knob options

- packages/elements-angular/elements/src/directives/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-snackbar/ino-snackbar.tsx
- packages/elements/src/components/ino-snackbar/readme.md
- packages/storybook/src/stories/ino-snackbar/ino-snackbar.stories.js
> feat(elements|ino-snackbar): add property to make snackbar stay visible on hover

- packages/elements/src/components/ino-select/ino-select.tsx
Closes #362 
- checked if MDC instance is defined
> fix(elements|ino-select): fix initialization error

- .github/pull_request_template.md
Closes #263
- Add checklist to pull request template.
> chore: add checklist to pull request template

- doc/framework-integration/angular-instructions.md
- packages/elements-angular/elements/README.md
- packages/elements-angular/elements/package.json
- packages/elements-angular/elements/schematics/collection.json
- packages/elements-angular/elements/schematics/ng-add/index.ts
- packages/elements-angular/elements/schematics/utils.ts
- packages/elements-angular/elements/tsconfig.schematics.json
- packages/elements-angular/elements/yarn.lock
- packages/elements-angular/package.json
Closes #390 
- Add schematic for angular CLI to automatically add our icons on `ng add @inovex.de/elements-angular`
> feat(elements-angular): add icons to angular.json on `ng add`

- packages/elements/src/components/ino-sidebar/ino-sidebar.tsx
- packages/elements/src/components/ino-sidebar/readme.md
🛠️ **Fixes:**
* `ino-sidebar`: Added null checks to prevent initialisation error
🎟️ **Closes #376**
> fix(elements|ino-sidebar): fix initialization error

- packages/elements/src/components/ino-datepicker/validator.ts
> fix(elements|ino-datepicker): max validation leads to recursion

- packages/elements/package.json
- packages/elements/src/interface.d.ts
Exposes our custom types and the component types.
- ...
> chore(elements): expose custom types

- packages/elements/src/components/ino-list-item/ino-list-item.scss
* Fixed positioning of the checkbox in `ino-list-item` component
🎟️ **Closes #276**
> fix(elements|ino-list-item): fix checkbox positioning

- packages/elements/src/components/ino-card/ino-card.scss
- packages/elements/src/components/ino-card/readme.md
- packages/storybook/custom-elements.json
* The background color and border of the card can now be customised using CSS variables
🎟️ **Closes #308** 
🎟️ **Closes #334**
> style(elements|ino-card): add css variables for the background color and border

- packages/elements/src/components/ino-select/ino-select.scss
- packages/elements/src/components/ino-select/ino-select.tsx
- packages/elements/src/components/ino-select/readme.md
- packages/storybook/custom-elements.json
- packages/storybook/src/stories/ino-select/ino-select.stories.ts
* added `ino-icon-leading` slot to `ino-select` component
🎟️ **Closes #233**
> feat(elements|ino-select): add slot for leading icon

- packages/elements-angular/elements/src/directives/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-tab-bar/ino-tab-bar.e2e.ts
- packages/elements/src/components/ino-tab-bar/ino-tab-bar.tsx
- packages/elements/src/components/ino-tab-bar/readme.md
- packages/storybook/custom-elements.json
- packages/storybook/src/stories/ino-tab-bar/ino-tab-bar.stories.ts
Closes #400
- add `autoFocus` property to ino-tab-bar component
> feat(elements|ino-tab-bar): add autoFocus property

- packages/storybook/config/manager-head.html
Closes #250
- change the `href` path of favicon
> fix(storybook): restore missing fav icon

- packages/elements/src/components/ino-input-file/ino-input-file.tsx
- packages/elements/src/components/ino-input-file/readme.md
- packages/storybook/src/stories/ino-input-file/ino-input-file.stories.ts
Closes #419 
- check if property dragAndDrop is set to true
- stop event in story
- adjust react docs
> fix(elements|ino-input-file): prevent drag and drop when set to false

- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-autocomplete/ino-autocomplete.e2e.ts
- packages/elements/src/components/ino-autocomplete/ino-autocomplete.tsx
Closes #443 
- open menu by keyboard press after option selection
> feat(elements|ino-autocomplete): provide keyboard support to open menu

- packages/elements-angular/elements/src/app-initialize.ts
- packages/elements-angular/elements/src/ino-elements.module.ts
- packages/elements/src/components/config.ts
- packages/elements/src/index.ts
- packages/elements/src/interface.d.ts
- packages/storybook/src/stories/docs/configuration.stories.mdx
- packages/storybook/src/stories/docs/framework-integration/angular-instructions.stories.mdx
> feat(elements): add global configuration

- packages/storybook/src/stories/docs/framework-integration/angular-instructions.stories.mdx
Closes (no issue opened)
- Just a path fix. The documentation refers to a path that doesn't exist.
> docs(elements-angular): fix assets path

- .github/workflows/release-canary.yml
- .github/workflows/test.yml
> chore(*): fix canary release pipeline

- packages/elements/src/components/ino-markdown-editor/ino-markdown-editor.scss
- packages/storybook/elements-stencil-docs.json
> fix(elements|ino-markdown-editor): fix focus state in preview mode

- packages/elements/src/components/ino-switch/ino-switch.tsx
Closes #...
- Adjust query logic
> fix(elements|ino-switch): do not update switches on same page

- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-currency-input/ino-currency-input.tsx
- packages/elements/src/components/ino-input/ino-input.e2e.ts
- packages/elements/src/components/ino-input/ino-input.tsx
> fix(elements|ino-input): prevent value from being set internally

- packages/elements/src/components/ino-datepicker/ino-datepicker.tsx
- apply `this.inline` check on leading slot
> fix(elements|ino-datepicker): fix datepicker hiding after input

- packages/elements/src/components/ino-datepicker/readme.md
- packages/elements/src/components/ino-header/readme.md
- packages/storybook/elements-stencil-docs.json
Closes #333
- revise readme of `ino-header`
- revise readme of `ino-datepicker`
> docs(elements): revise docs of ino-header and ino-datepicker

- packages/elements/src/components/ino-list-item/ino-list-item.scss
> fix(elements|ino-list-item): fix vertical alignment of trailing element

- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-chip/ino-chip.tsx
- packages/elements/src/components/ino-chip/readme.md
- packages/elements/src/components/ino-snackbar/ino-snackbar.tsx
- packages/elements/src/components/ino-snackbar/readme.md
- packages/storybook/elements-stencil-docs.json
- packages/storybook/src/stories/ino-chip/ino-chip.stories.ts
Relates to #403
- make usage of default <slot />
- add deprication warnings
- adjust stories
> feat(elements|ino-chip): use default slot

- packages/elements/src/components/ino-currency-input/ino-currency-input.tsx
> fix(elements|ino-currency-input): allow `0` in `value`

- packages/elements/src/components/ino-autocomplete/ino-autocomplete.scss
- packages/storybook/src/stories/ino-autocomplete/ino-autocomplete.stories.ts
Closes #569 
- Change styling of options menu
> fix(elements|ino-autocomplete): fix wrong menu positioning if helper text exists

- packages/elements/src/components/ino-currency-input/ino-currency-input.e2e.ts
Additional test for zero values
> test(elements|ino-currency-input): allow 0 input

- packages/storybook/src/stories/docs/contributing/04-developing-components.stories.mdx
- update our component development guide
> docs: update component development docs

- packages/storybook/elements-stencil-docs.json
- packages/storybook/src/stories/ino-select/ino-select.stories.ts
Part of #574 
- reformat stories of ino-select to follow unified story format
> refactor(storybook|ino-select): reformat stories

- packages/storybook/src/stories/ino-radio-group/ino-radio-group.stories.ts
Part of #574 
- reformat stories of ino-radio-group to follow unified story format
> refactor(storybook|ino-radio-group): reformat stories

- packages/storybook/src/stories/ino-option/ino-option.stories.ts
- packages/storybook/src/stories/template-generator.ts
Part of #574 
- reformat stories of ino-option to follow unified story format
> refactor(storybook|ino-option): reformat stories

- packages/storybook/src/stories/ino-dialog/ino-dialog.scss
- packages/storybook/src/stories/ino-dialog/ino-dialog.stories.ts
Part of #574 
- reformat stories of ino-dialog to follow unified story format
> refactor(storybook|ino-dialog): reformat stories

- packages/storybook/src/stories/ino-switch/ino-switch.stories.ts
Part of #574 
- reformat stories of ino-switch to follow unified story format
> refactor(storybook|ino-switch): reformat stories

- packages/storybook/src/stories/ino-input/ino-input.stories.ts
Part of #574 
- reformat stories of ino-input to follow unified story format
> refactor(storybook|ino-input): reformat stories

- packages/elements-angular-example/src/app/app.component.html
- packages/elements-angular-example/src/app/app.component.scss
- packages/elements-angular-example/src/app/app.component.spec.ts
- packages/elements-angular-example/src/app/app.component.ts
- packages/elements-angular-example/src/app/app.module.ts
- packages/elements-angular/elements/package.json
- packages/elements-angular/elements/src/directives/control-value-accesors/value-accessor.directive.ts
Closes #638
- add `setDisabledState` method
- extend example-angular project with basic reactive form
> feat(elements-angular): support disable state handling in ControlValueAccessors

- .github/workflows/semantic-pull-request.yml
Part of #647 
Adds a new semantic pull request bot. Needs one initial merge into master before taking effect.
> ci: add semantic pull request bot

- packages/elements/src/components/ino-checkbox/ino-checkbox.scss
- packages/elements/src/components/ino-checkbox/readme.md
- packages/storybook/elements-stencil-docs.json
- yarn.lock
Closes #681 
Applies new styling to ino-checkbox.
Color variables not set jet.
> style(elements|ino-checkbox): update design

- packages/elements/src/components/ino-switch/ino-switch.scss
- packages/storybook/elements-stencil-docs.json
Closes #685 
- update design without changing its API
> style(elements|ino-switch): update design

- packages/elements/src/components/ino-button/ino-button.scss
- outlined state gets transparent background
- update color variables
Closes #709
> style(elements|ino-button): make outlined background transparent

- .github/workflows/deploy-version.yml
Closes #688
- add new CI Action step to create a `latest` symlink to the new version
> ci: support symlink to the latest version

- packages/storybook/src/stories/docs/contributing/04-developing-components.stories.mdx
> docs(storybook): add dev documentation about custom properties

- .github/workflows/deploy-version.yml
- .github/workflows/release-canary.yml
- lerna.json
> ci: fix release pipeline

- .github/workflows/artifacts-download/action.yml
- .github/workflows/deploy-version.yml
- .versionrc
- package.json
- packages/elements-angular-example/.versionrc
- packages/elements-angular/.versionrc
- packages/elements-react-example/.versionrc
- packages/elements-react/.versionrc
- packages/elements-vue-example/.versionrc
- packages/elements-vue/.versionrc
- packages/elements/.versionrc
- packages/landingpage/.versionrc
- packages/storybook/.versionrc
Closes #747 
Taken from the issues:
- [ ] Github Release
- [ ] Artifacts are linked to the Github Release
> ci: make several improvements of the release pipeline

- lerna.json
- nx.json
- package.json
- packages/elements/src/components/ino-button/ino-button.scss
Closes #753 
- add NX as dependency
- activate NX for lerna
- scripts like `build`, `test` and `lint` will be cached and therefore only be executed if anything changed since the last execution
> chore: add nx

- .github/workflows/deploy-unicorn.yml
- .github/workflows/test.yml
- use `workflow_call` trigger 
- call unicorn deployment from `test.yml`
- clean up / simplify cache logic
- provide deployment link in pull request
> ci: run unicorn deployment by workflow_call trigger

- packages/landingpage-new/components/layout/footer.tsx
- packages/landingpage-new/components/layout/header.tsx
Closes #777
For some reason, the `priority` property of the `<Image>` component was at fault.
> fix(landingpage): styles disappearing on navigation

- packages/landingpage-new/next.config.js
- packages/landingpage-new/package.json
- packages/landingpage-new/pages/_app.tsx
- yarn.lock
> fix(landingpage): make icons available

- packages/elements/src/util/icons.ts
- packages/landingpage-new/.eslintrc.json
- packages/landingpage-new/components/home/header/header.tsx
- packages/landingpage-new/components/home/header/install-chips.tsx
- packages/landingpage-new/components/layout/header.tsx
- packages/landingpage-new/next.config.js
- packages/landingpage-new/package.json
- yarn.lock
> chore(landingpage): upgrade next.js to v13

- packages/landingpage-new/components/home/header/header.tsx
- packages/landingpage-new/components/home/header/install-chips.tsx
- packages/landingpage-new/components/layout/header.tsx
- packages/landingpage-new/next.config.js
- packages/landingpage-new/tsconfig.json
- packages/landingpage-new/utils/hooks/use-base-path.ts
> fix(landingpage): adjust image base paths

- packages/elements/package.json
- packages/elements/src/components/ino-datepicker/ino-datepicker.scss
- yarn.lock
Closes #776 
- Updating to the newest flatpickr version seems to fix the issue
- Improved month picker styles
> fix(elements|ino-datepicker): prevent month picker from skipping months

- .github/workflows/deploy-version.yml
- Add setup node step from `dependencies-install` to release pipeline
> ci: add setup node to release pipeline

- .github/workflows/deploy-unicorn.yml
- solve issue when both commit sha are equal
- when both sha are equal allow unicorn deployment
> ci: improve unicorn deployment

- packages/elements-react-example/package.json
- packages/elements-react-example/src/assets/elements.svg
- packages/elements-react-example/src/login-form-app/index.tsx
- packages/elements-vue-example/package.json
Closes #811 
- delete references to other parts of monorepo
- added sass dependency in react example project
- rename "serve" scripts to "start"
> fix: fix vue and react example project for stackblitz

- packages/landingpage-new/components/layout/linkItem.module.scss
- packages/landingpage-new/components/layout/linkItem.tsx
- packages/landingpage-new/components/layout/navbar.module.scss
- packages/landingpage-new/components/layout/navbar.tsx
- packages/landingpage-new/utils/routes.tsx
Closes #849 
- submenu in header with `ino-popover`
> feat(landingpage): add sub navigation

- packages/landingpage-new/components/getting-started/layout.module.scss
> feat(landingpage): add styling to the getting started tables

- packages/landingpage-new/components/layout/localeSwitcher.tsx
- packages/landingpage-new/next.config.mjs
- packages/landingpage-new/pages/[lang]/index.tsx
- packages/landingpage-new/pages/index.tsx
- packages/landingpage-new/translations/useDefaultLocale.ts
> fix(landingpage): language switch not working

- packages/elements-angular/elements/src/directives/proxies.ts
- packages/elements-vue/src/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/base/_new-theme.scss
- packages/elements/src/components/ino-carousel-slide/ino-carousel-slide.scss
- packages/elements/src/components/ino-carousel-slide/ino-carousel-slide.tsx
- packages/elements/src/components/ino-carousel-slide/readme.md
- packages/elements/src/components/ino-carousel/ino-carousel.e2e.ts
- packages/elements/src/components/ino-carousel/ino-carousel.scss
- packages/elements/src/components/ino-carousel/ino-carousel.tsx
- packages/elements/src/components/ino-carousel/readme.md
- packages/storybook/config/main.js
- packages/storybook/elements-stencil-docs.json
- packages/storybook/src/stories/ino-carousel/ino-carousel.stories.ts
- packages/storybook/src/types/images.d.ts
> feat(elements|ino-carousel): add stepper to indicate currently displayed slide

- packages/elements/src/components/ino-card/ino-card.scss
Closes #787 
The default color was set to #fff (white), now its primary blue base.
> fix(elements|ino-card): selection state not working properly

- packages/elements/src/components/ino-fab/ino-fab.tsx
> fix(elements|ino-tooltip): label not updating on change

- assets/logo/inovex-logo.svg
- packages/landingpage-new/public/inovex-logo.svg
> refactor(landingpage): update inovex-logo in footer

- packages/elements-angular/elements/src/directives/proxies.ts
- packages/elements-vue/src/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-chip/ino-chip.scss
- packages/elements/src/components/ino-chip/ino-chip.tsx
- packages/elements/src/components/ino-chip/readme.md
- packages/storybook/elements-stencil-docs.json
- packages/storybook/src/stories/ino-chip/ino-chip.stories.ts
> feat(elements|ino-chip): add clickable option

- packages/elements/src/components/ino-range/ino-range.tsx
> fix(elements|ino-range): prevent error on value change

- packages/landingpage-new/components/home/faq-section/faq-section.tsx
- packages/landingpage-new/translations/locales/de/home.json
- packages/landingpage-new/translations/locales/en/home.json
- add two more Questions
- What are the inovex Elements?
- Why doesn't everyone use such a Web Components library?
- Improve maintainability
> feat(landingpage): improve FAQ section

- packages/elements/src/components/ino-input/ino-input.scss
- packages/elements/src/components/ino-input/ino-input.tsx
> style(elements|ino-input): update outline variant

- packages/landingpage/components/layout/attributions.module.scss
- packages/landingpage/components/layout/attributions.tsx
- packages/landingpage/translations/locales/de/common.json
- packages/landingpage/translations/locales/en/common.json
Some prpwork before we finally finish with #987. Please merge this PR asap.
> chore: add legal links

- packages/storybook/src/stories/ino-dialog/ino-dialog.stories.ts
> refactor(elements|ino-dialog): adjust cancelText in storybook

- packages/elements/src/components/ino-radio-group/ino-radio-group.tsx
- packages/storybook/elements-stencil-docs.json
- packages/storybook/src/stories/ino-radio-group/ino-radio-group.stories.ts
> fix(elements|ino-radio-group): trigger valueChange upon clicking

- README.md
- packages/elements/README.md
- packages/landingpage/components/layout/attributions.tsx
- packages/landingpage/mdx/getting-started/angular-guide.de.mdx
- packages/landingpage/mdx/getting-started/angular-guide.en.mdx
- packages/landingpage/mdx/getting-started/javascript-guide.de.mdx
- packages/landingpage/mdx/getting-started/javascript-guide.en.mdx
- packages/landingpage/mdx/getting-started/react-guide.de.mdx
- packages/landingpage/mdx/getting-started/react-guide.en.mdx
- packages/landingpage/mdx/getting-started/vue-guide.de.mdx
- packages/landingpage/mdx/getting-started/vue-guide.en.mdx
- packages/landingpage/translations/locales/de/about.json
- packages/landingpage/translations/locales/de/common.json
- packages/landingpage/translations/locales/de/explore.json
- packages/landingpage/translations/locales/de/home.json
- packages/landingpage/translations/locales/en/about.json
- packages/landingpage/translations/locales/en/common.json
- packages/landingpage/translations/locales/en/explore.json
- packages/landingpage/translations/locales/en/home.json
- packages/storybook/src/stories/docs/contributing/01-high-level-overview.stories.mdx
- packages/storybook/src/stories/docs/contributing/03-team-organization.stories.mdx
- packages/storybook/src/stories/docs/contributing/06-issue-tracking.stories.mdx
- packages/storybook/src/stories/docs/contributing/10-updating-dependencies.stories.mdx
- packages/storybook/src/stories/docs/framework-integration/angular-instructions.stories.mdx
- packages/storybook/src/stories/docs/framework-integration/javascript-instructions.stories.mdx
- packages/storybook/src/stories/docs/framework-integration/react-instructions.stories.mdx
- packages/storybook/src/stories/docs/framework-integration/vue-instructions.stories.mdx
- packages/storybook/src/stories/docs/stylesheet.stories.mdx
- packages/storybook/src/stories/docs/welcome.stories.mdx
> refactor(elements): correct brand name from 'Elements and Inovex' to 'inovex Elements'

- packages/landingpage/utils/contributors.ts
This PR changes my status as a contributor from inactive to active on our website's landingpage.
> refactor(landingpage): remove contributor isInactive flag 

- packages/elements/src/components/ino-autocomplete/ino-autocomplete.scss
> refactor(elements|ino-autocomplete): update design

- .github/workflows/deploy-landingpage.yml
- exclude hosted-versions.json from being deleted for our version selector in #1022
> refactor(elements): exclude hosted-versions.json from clean up

- packages/elements/src/components/ino-switch/ino-switch.scss
- packages/storybook/src/stories/ino-switch/ino-switch.stories.ts
Closes #972 
fix disabled display when also checked
https://github.com/inovex/elements/assets/81302108/489715ab-dbab-47e8-80a7-64f550469a34
> refactor(elements|ino-switch): fix disabled state not displaying correctly

- packages/landingpage/components/home/core-aspects/core-aspects.module.scss
closes no linked issue
Fixed text overflow issues, notably in the German version, by refining breakpoints and adjusting the container height to fit the text.
**Before:**
https://github.com/inovex/elements/assets/81302108/d23b1ad5-36a1-4a94-9fe4-0ef6cee1d2dd
**After:**
https://github.com/inovex/elements/assets/81302108/8ce7e7ba-d5f4-4ea9-b706-f86c3d64cbb5
> refactor(landingpage): tweak core-aspect responsiveness

- packages/landingpage/components/layout/attributions.module.scss
- packages/landingpage/components/layout/attributions.tsx
- packages/landingpage/components/layout/footer/desktop/footer.desktop.module.scss
- packages/landingpage/components/layout/footer/desktop/footer.desktop.tsx
- packages/landingpage/components/layout/footer/footer.module.scss
- packages/landingpage/components/layout/footer/footer.tsx
- packages/landingpage/components/layout/footer/mobile/footer.mobile.module.scss
- packages/landingpage/components/layout/footer/mobile/footer.mobile.tsx
- packages/landingpage/components/layout/header/mobile/header.mobile.tsx
- packages/landingpage/components/layout/linkItem.module.scss
- packages/landingpage/components/layout/linkItem.tsx
- packages/landingpage/translations/locales/de/common.json
- packages/landingpage/translations/locales/en/common.json
Closes #998 
Currently working with no design to abide to. More traditional variant of this is in #1053 
Preview:
https://github.com/inovex/elements/assets/81302108/a43c316a-a5be-40f2-ab4a-8348d081630b
> refactor(landingpage): tweak footer design

- packages/elements-angular/src/generated/components.ts
- packages/elements-vue/src/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-segment-button/ino-segment-button.tsx
- packages/elements/src/components/ino-segment-button/readme.md
- packages/storybook/elements-stencil-docs.json
- packages/storybook/src/stories/ino-segment-button/ino-segment-button.stories.ts
> feat(elements|ino-segment-button): add type property

- packages/elements-angular/src/generated/components.ts
- packages/elements-vue/src/proxies.ts
- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-dialog/ino-dialog.tsx
- packages/elements/src/components/ino-dialog/readme.md
- packages/storybook/elements-stencil-docs.json
- packages/storybook/src/stories/ino-dialog/ino-dialog.stories.ts
> refactor(elements|ino-dialog): accessible ino-dialog

- packages/landingpage/pages/[lang]/library/patterns/index.tsx
- packages/ui-patterns/README.md
- packages/ui-patterns/package.json
- packages/ui-patterns/src/index.ts
- packages/ui-patterns/vite.config.ts
> feat(elements): move static html to ui-patterns bundle build output

- packages/landingpage/components/layout.tsx
- packages/landingpage/styles/globals.css
Closes #1085 
- adds a blured background pattern to all landingpage pages
https://github.com/inovex/elements/assets/103122411/b425585e-3519-436b-8761-83e40c3520de
> feat(landingpage): add blur bg pattern

- .github/workflows/artifacts-download/action.yml
- .github/workflows/artifacts-upload/action.yml
- .github/workflows/deploy-landingpage.yml
- .github/workflows/deploy-unicorn.yml
- .github/workflows/semantic-pull-request.yml
- .lintstagedrc
- .prettierignore
- packages/elements-angular/ng-package.json
- packages/elements-react/tsconfig.json
- packages/elements-vue-example/src/App.vue
- packages/elements-vue-example/src/components/ContactForm.vue
- packages/elements-vue-example/src/components/ImageGallery.vue
- packages/elements-vue-example/src/components/SampleDialog.vue
- packages/elements-vue-example/src/components/ToDoList.vue
- packages/elements-vue-example/src/components/VCard.vue
- packages/elements-vue/tsconfig.json
- packages/elements/tsconfig.json
- packages/elements/tsconfig.lib.json
- packages/landingpage/translations/locales/de/explore.json
- packages/landingpage/translations/locales/en/explore.json
- packages/landingpage/tsconfig.json
- packages/ui-patterns-playground/.eslintrc.cjs
- packages/ui-patterns/.eslintrc.cjs
Ran the formatter once for all files. Usually, the formatter only checks changed files.
> refactor: run formatter for all files

- packages/storybook/config/main.ts
- packages/storybook/package.json
- yarn.lock
- bump storybook to latest
- improve bundling speed by disabling docs-addon of essentials
> deps: bump storybook to 7.6.12

- packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.tsx
> fix(elements|ino-nav-drawer): prevent trapping of focus

- packages/landingpage/utils/hooks/useStorybookUrl.ts
The storybook URL was changed after the storybook upgrade.
> refactor(landingpage): update storybook welcome url

- .github/workflows/deploy-storybook.yml
> ci: fix storybook deployment by removing outdated npm command

- packages/elements/src/components/ino-input/ino-input.e2e.ts
- packages/elements/src/components/ino-input/ino-input.tsx
Closes #1176 
- provide min max border check for arrow click
> fix(elements/ino-input): enforce min max constrains on arrow icon click

- .github/workflows/project-management.yml
- add the label "new" to an opened issue
> chore: add label "new" to opened issues

- packages/landingpage/app/not-found.tsx
Closes #1309 
- replace route when trailing slash is applied
> fix(landingpage): prevent redirection to 404

- packages/landingpage/app/[lang]/library/patterns/client.tsx
Closes #1166
Preview: 
https://github.com/inovex/elements/assets/81302108/a3b9f7e5-31fc-472a-9f49-93897576578b
> feat(landingpage): add Tailwind Integration guide

- nx.json
- package.json
- packages/elements-angular-example/project.json
- packages/elements-angular/project.json
- packages/elements-react-example/project.json
- packages/elements-react/project.json
- packages/elements-vue-example/project.json
- packages/elements-vue/project.json
- packages/elements/project.json
- packages/landingpage/project.json
- packages/storybook/project.json
- packages/ui-patterns-playground/project.json
- packages/ui-patterns/project.json
- project.json
Closes #1091 
- add shared target "clean" in `nx.json`
- hide `scripts` in `package.json` from nx
> refactor: optimize clean up script for outputs and node_modules

- packages/elements/src/components/ino-icon/ino-icon.scss
> revert(elements/ino-icon): improve vertical alignment

- packages/elements/src/components.d.ts
- packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.tsx
- packages/elements/src/components/ino-nav-drawer/readme.md
- packages/storybook/elements-stencil-docs.json
> docs(elements/ino-nav-drawer): update ino-nav-drawer docs to clarify usage for navigation
